//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Owin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_User { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string UserRealName { get; set; }
        public string UserPatronymic { get; set; }
        public string UserOldSurname { get; set; }
        public string email { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserGroup_id { get; set; }
        public Nullable<int> UserType_id { get; set; }
        public Nullable<float> Hours { get; set; }
        public string comment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Boss_Id { get; set; }
        public Nullable<int> Boss_Id2 { get; set; }
        public Nullable<int> Boss_Id3 { get; set; }
        public string ComputerName { get; set; }
        public string UniqueUserID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string PAFirmID { get; set; }
        public string ExternalCaseComments { get; set; }
        public string CasesCriteria { get; set; }
        public Nullable<bool> NotWorking { get; set; }
        public string Hours_comment { get; set; }
        public Nullable<float> Hours_Employee { get; set; }
        public Nullable<int> Vacation_days { get; set; }
        public Nullable<float> Vacation_hours { get; set; }
        public Nullable<float> Vacation_totalHours { get; set; }
        public Nullable<bool> IsOfficially { get; set; }
        public Nullable<bool> ShowTM { get; set; }
        public Nullable<bool> ShowClosedCases { get; set; }
        public Nullable<bool> ShowOnlyTM { get; set; }
        public string PersonalSkype { get; set; }
        public string WorkSkype { get; set; }
        public string PersonalEmails { get; set; }
        public string ContactPhones { get; set; }
        public string ServerAccount { get; set; }
        public string ServerPassword { get; set; }
        public Nullable<bool> AllowCashOperations { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string InfoPageName { get; set; }
        public string ImageLink { get; set; }
        public string EmployeeInfo { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> FIRMID { get; set; }
        public Nullable<System.DateTime> WorkingSince { get; set; }
        public Nullable<System.DateTime> TestNextAttemptDate { get; set; }
        public Nullable<bool> NeedCaptchaInput { get; set; }
        public Nullable<bool> RestrictedWithoutEmailAuth { get; set; }
        public bool AllowRemoteAccess { get; set; }
        public bool AllowRemoteAccessExclusively { get; set; }
        public byte[] tstamp { get; set; }
        public bool IsIntern { get; set; }
        public string WorkContactNumbers { get; set; }
        public string RegistrationAddress { get; set; }
        public string FactAddress { get; set; }
        public string Education { get; set; }
        public string Photo_link { get; set; }
        public string CV_link { get; set; }
        public Nullable<System.DateTime> WorkingOut { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string SignatureLink { get; set; }
        public Nullable<bool> IsAdditionalVerification { get; set; }
        public Nullable<bool> PassedText { get; set; }
    }
}
